# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "dbornitz-tfstate-1ef8"
    dynamodb_table = "app-state"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "us-east-2"
  }
}
